name: Docs2Pages
on: push

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - uses: abatilo/actions-poetry@v2
    - name: install
      run: poetry install --with docs
      #run: poetry install -E amazon -E docs
    - name: Build documentation
      run: |
        mkdir docs
        touch docs/.nojekyll
        cd docs/source
        poetry run sphinx-build -b html . _build
        cp -r _build/* ../../docs/
    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: gh-pages
        folder: docs